BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "CLASSROOM_has_COURSE" (
	"fName"	VARCHAR(20) NOT NULL,
	"lName"	VARCHAR(20) NOT NULL,
	"userCode"	VARCHAR(10) NOT NULL UNIQUE,
	"passCode"	VARCHAR(25) NOT NULL,
	PRIMARY KEY("userCode")
);
CREATE TABLE IF NOT EXISTS "USER" (
	"idUser"	VARCHAR(10) NOT NULL UNIQUE,
	"fName"	VARCHAR(25) NOT NULL,
	"lName"	VARCHAR(25) NOT NULL,
	"passCode"	VARCHAR(40) NOT NULL,
	"userType"	SMALLINT NOT NULL,
	"schedule"	VARCHAR(45) NOT NULL,
	PRIMARY KEY("idUser")
);
CREATE TABLE IF NOT EXISTS "SECTION" (
	"idSection"	INT NOT NULL UNIQUE,
	"sectionDay"	DATE NOT NULL,
	"sectionTime"	TIME NOT NULL,
	PRIMARY KEY("idSection")
);
CREATE TABLE IF NOT EXISTS "CLASSROOM" (
	"idClassroom"	INT NOT NULL UNIQUE,
	"amtSeats"	INT NOT NULL,
	"equipType"	VARCHAR(20),
	PRIMARY KEY("idClassroom")
);
CREATE TABLE IF NOT EXISTS "COURSE" (
	"idCourse"	INTEGER NOT NULL UNIQUE,
	"idReqCourse"	INT,
	PRIMARY KEY("idCourse")
);
CREATE TABLE IF NOT EXISTS "SCHED" (
	"USER_idUser"	VARCHAR(10) NOT NULL UNIQUE,
	"monday"	BOOLEAN NOT NULL,
	"tuesday"	BOOLEAN NOT NULL,
	"wednesday"	BOOLEAN NOT NULL,
	"thursday"	BOOLEAN NOT NULL,
	"friday"	BOOLEAN NOT NULL,
	PRIMARY KEY("USER_idUser")
);
COMMIT;
