/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PJSTGUIs;

/**
 *
 * @author Joe Fromuth 
 */
public class jfInstructorPreferencesPanel extends javax.swing.JPanel {

    /**
     * Creates new form jfInstructorPreferencesPanel
     */
    public jfInstructorPreferencesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAbility = new javax.swing.JLabel();
        jtTimes = new javax.swing.JTextField();
        jtPreferences = new javax.swing.JTextField();
        jtAbility = new javax.swing.JTextField();
        jbConfirm = new javax.swing.JButton();
        jlTitle = new javax.swing.JLabel();
        jbConfirm1 = new javax.swing.JButton();
        jlTimes = new javax.swing.JLabel();
        jlPreferences = new javax.swing.JLabel();

        jlAbility.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAbility.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAbility.setText("Instructor Ability");
        jlAbility.setToolTipText("");

        jtTimes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtTimes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtTimes.setToolTipText("");
        jtTimes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtPreferences.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtPreferences.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtPreferences.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtAbility.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtAbility.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtAbility.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtAbility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAbilityActionPerformed(evt);
            }
        });

        jbConfirm.setBackground(new java.awt.Color(0, 0, 153));
        jbConfirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirm.setText("Confirm");

        jlTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("Instructor");

        jbConfirm1.setBackground(new java.awt.Color(0, 0, 153));
        jbConfirm1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbConfirm1.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirm1.setText("Exit");

        jlTimes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlTimes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTimes.setText("Instructor Times");

        jlPreferences.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlPreferences.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPreferences.setText("Instructor Preferences");
        jlPreferences.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jlTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirm1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlAbility)
                    .addComponent(jlTimes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlPreferences)
                        .addComponent(jtTimes)
                        .addComponent(jtPreferences)
                        .addComponent(jtAbility, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlTitle)
                .addGap(18, 18, 18)
                .addComponent(jlTimes)
                .addGap(18, 18, 18)
                .addComponent(jtTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlPreferences)
                .addGap(32, 32, 32)
                .addComponent(jtPreferences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlAbility)
                .addGap(29, 29, 29)
                .addComponent(jtAbility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirm)
                    .addComponent(jbConfirm1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtAbilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAbilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAbilityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConfirm;
    private javax.swing.JButton jbConfirm1;
    private javax.swing.JLabel jlAbility;
    private javax.swing.JLabel jlPreferences;
    private javax.swing.JLabel jlTimes;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTextField jtAbility;
    private javax.swing.JTextField jtPreferences;
    private javax.swing.JTextField jtTimes;
    // End of variables declaration//GEN-END:variables
}
