package PJSTGUIs;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jake_Gaming_PC
 */
public class jfInstructorTimesPanel extends javax.swing.JPanel {

    /**
     * Creates new form jfInstructorTimesPanel
     */
    public jfInstructorTimesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFriday = new javax.swing.JLabel();
        jlSaturday = new javax.swing.JLabel();
        jlSunday = new javax.swing.JLabel();
        jspTimes = new javax.swing.JScrollPane();
        jtTimes = new javax.swing.JTextArea();
        jbSend = new javax.swing.JButton();
        jlTitle = new javax.swing.JLabel();
        jlMonday = new javax.swing.JLabel();
        jbSave = new javax.swing.JButton();
        jlTuesday = new javax.swing.JLabel();
        jbExit = new javax.swing.JButton();
        jlWednesday = new javax.swing.JLabel();
        jlThursday = new javax.swing.JLabel();

        jlFriday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlFriday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFriday.setText("Friday");

        jlSaturday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlSaturday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSaturday.setText("Saturday");

        jlSunday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlSunday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSunday.setText("Sunday");
        jlSunday.setToolTipText("");

        jtTimes.setColumns(20);
        jtTimes.setRows(5);
        jtTimes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jspTimes.setViewportView(jtTimes);

        jbSend.setBackground(new java.awt.Color(0, 0, 153));
        jbSend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSend.setForeground(new java.awt.Color(255, 255, 255));
        jbSend.setText("Send to Registrar");

        jlTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("Instructor Times");

        jlMonday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlMonday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMonday.setText("Monday");

        jbSave.setBackground(new java.awt.Color(0, 0, 153));
        jbSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSave.setForeground(new java.awt.Color(255, 255, 255));
        jbSave.setText("Save");

        jlTuesday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlTuesday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTuesday.setText("Tuesday");

        jbExit.setBackground(new java.awt.Color(0, 0, 153));
        jbExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(255, 255, 255));
        jbExit.setText("Exit");

        jlWednesday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlWednesday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlWednesday.setText("Wednesday");

        jlThursday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlThursday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlThursday.setText("Thursday");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitle)
                .addGap(255, 255, 255))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSunday)
                    .addComponent(jlSaturday)
                    .addComponent(jlFriday)
                    .addComponent(jlThursday)
                    .addComponent(jlWednesday)
                    .addComponent(jlTuesday)
                    .addComponent(jlMonday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSend)
                        .addGap(86, 86, 86)
                        .addComponent(jbExit))
                    .addComponent(jspTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jspTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jlMonday)
                        .addGap(18, 18, 18)
                        .addComponent(jlTuesday)
                        .addGap(18, 18, 18)
                        .addComponent(jlWednesday)
                        .addGap(21, 21, 21)
                        .addComponent(jlThursday)
                        .addGap(18, 18, 18)
                        .addComponent(jlFriday)
                        .addGap(18, 18, 18)
                        .addComponent(jlSaturday)
                        .addGap(18, 18, 18)
                        .addComponent(jlSunday)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbExit)
                    .addComponent(jbSend)
                    .addComponent(jbSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbSend;
    private javax.swing.JLabel jlFriday;
    private javax.swing.JLabel jlMonday;
    private javax.swing.JLabel jlSaturday;
    private javax.swing.JLabel jlSunday;
    private javax.swing.JLabel jlThursday;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlTuesday;
    private javax.swing.JLabel jlWednesday;
    private javax.swing.JScrollPane jspTimes;
    private javax.swing.JTextArea jtTimes;
    // End of variables declaration//GEN-END:variables
}
