/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PJSTGUIs;

/**
 *
 * @author Jake_Gaming_PC
 */
public class jfRegistrarCampusPanel extends javax.swing.JPanel {

    /**
     * Creates new form jfRegistrarCampusPanel
     */
    public jfRegistrarCampusPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtCampus = new javax.swing.JTextField();
        jlCampus = new javax.swing.JLabel();
        jlTerm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbSave = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jtTerm = new javax.swing.JTextField();

        jtCampus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtCampus.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtCampus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        jlCampus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCampus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCampus.setText("Campus");

        jlTerm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlTerm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlTerm.setText("Term");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Campus");

        jbSave.setBackground(new java.awt.Color(0, 0, 153));
        jbSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSave.setForeground(new java.awt.Color(255, 255, 255));
        jbSave.setText("Save");

        jbExit.setBackground(new java.awt.Color(0, 0, 153));
        jbExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(255, 255, 255));
        jbExit.setText("Exit");

        jtTerm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtTerm.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtTerm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlTerm)
                                .addComponent(jlCampus))
                            .addComponent(jbSave))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCampus)
                            .addComponent(jtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbExit, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCampus))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTerm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSave)
                    .addComponent(jbExit))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlCampus;
    private javax.swing.JLabel jlTerm;
    private javax.swing.JTextField jtCampus;
    private javax.swing.JTextField jtTerm;
    // End of variables declaration//GEN-END:variables
}
