/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PJSTGUIs;

/**
 *
 * @author Joe Fromuth 
 */
public class jfRevisedSchedulePanel extends javax.swing.JPanel {

    /**
     * Creates new form jfRevisedSchedulePanel
     */
    public jfRevisedSchedulePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlProgramCoord = new javax.swing.JLabel();
        jlRevisedSchedule = new javax.swing.JLabel();
        jtSchedule = new javax.swing.JTextField();
        jbExit = new javax.swing.JButton();
        jbConfirm = new javax.swing.JButton();

        jlProgramCoord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlProgramCoord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlProgramCoord.setText("Program Coordinator");

        jlRevisedSchedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlRevisedSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRevisedSchedule.setText("See Revised Schedule");

        jtSchedule.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtSchedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        jbExit.setBackground(new java.awt.Color(0, 0, 153));
        jbExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(255, 255, 255));
        jbExit.setText("Exit");

        jbConfirm.setBackground(new java.awt.Color(0, 0, 153));
        jbConfirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirm.setText("Confirm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConfirm)
                        .addGap(173, 173, 173)
                        .addComponent(jbExit))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlProgramCoord)
                                .addComponent(jlRevisedSchedule))
                            .addGap(82, 82, 82))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlProgramCoord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlRevisedSchedule)
                .addGap(18, 18, 18)
                .addComponent(jtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirm)
                    .addComponent(jbExit))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConfirm;
    private javax.swing.JButton jbExit;
    private javax.swing.JLabel jlProgramCoord;
    private javax.swing.JLabel jlRevisedSchedule;
    private javax.swing.JTextField jtSchedule;
    // End of variables declaration//GEN-END:variables
}
