/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PJSTGUIs;

import IST261.*;

/**
 *
 * @author Joey
 */
public class jpLogin extends javax.swing.JPanel {

    /**
     * Creates new form jpLogin
     */
    public jpLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jbExit = new javax.swing.JButton();
        jlLogin = new javax.swing.JLabel();
        jtLogin = new javax.swing.JTextField();
        jpaPassword = new javax.swing.JPasswordField();
        jlPassword = new javax.swing.JLabel();
        jbConfirm = new javax.swing.JButton();

        jlTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("User Login");

        jbExit.setBackground(new java.awt.Color(0, 0, 153));
        jbExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(255, 255, 255));
        jbExit.setText("Exit");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jlLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogin.setText("Login");

        jtLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        jpaPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jpaPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpaPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jpaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpaPasswordActionPerformed(evt);
            }
        });

        jlPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPassword.setText("Password");

        jbConfirm.setBackground(new java.awt.Color(0, 0, 153));
        jbConfirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirm.setText("Confirm");
        jbConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLogin)
                            .addComponent(jlPassword))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpaPassword)
                            .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTitle)
                        .addGap(85, 85, 85)))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jbConfirm)
                .addGap(47, 47, 47)
                .addComponent(jbExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogin)
                    .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirm)
                    .addComponent(jbExit))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmActionPerformed
        // TODO add your handling code here:
        
        String password = new String(jpaPassword.getPassword());
        
       SQLiteDatabase dbTemp = new SQLiteDatabase();
        System.out.println(dbTemp.getFilePath());
        
        dbTemp.connectDatabase();
        
        System.out.println(dbTemp.getMyCon());
        
       dbTemp.checkLoginInfo(jtLogin.getText(), password);
       
       
      
    }//GEN-LAST:event_jbConfirmActionPerformed

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbExitActionPerformed

    private void jpaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpaPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpaPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConfirm;
    private javax.swing.JButton jbExit;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPasswordField jpaPassword;
    private javax.swing.JTextField jtLogin;
    // End of variables declaration//GEN-END:variables
}
