package PJSTGUIs;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Joey
 */
public class jpMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form jpMainPanel
     */
    public jpMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInstructorInfo1 = new PJSTGUIs.jpInstructorInfo();
        jpRevisedSchedule1 = new PJSTGUIs.jpRevisedSchedule();
        jpInstructorInfo2 = new PJSTGUIs.jpInstructorInfo();
        jpInstructorInfo3 = new PJSTGUIs.jpInstructorInfo();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpRevisedSchedule2 = new PJSTGUIs.jpRevisedSchedule();
        jpInstructorInfo4 = new PJSTGUIs.jpInstructorInfo();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jpInstructorInfo5 = new PJSTGUIs.jpInstructorInfo();
        jpRevisedSchedule3 = new PJSTGUIs.jpRevisedSchedule();

        jTabbedPane1.addTab("tab1", jpRevisedSchedule2);
        jTabbedPane1.addTab("tab2", jpInstructorInfo4);

        jTabbedPane2.addTab("tab1", jpInstructorInfo5);
        jTabbedPane2.addTab("tab2", jpRevisedSchedule3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private PJSTGUIs.jpInstructorInfo jpInstructorInfo1;
    private PJSTGUIs.jpInstructorInfo jpInstructorInfo2;
    private PJSTGUIs.jpInstructorInfo jpInstructorInfo3;
    private PJSTGUIs.jpInstructorInfo jpInstructorInfo4;
    private PJSTGUIs.jpInstructorInfo jpInstructorInfo5;
    private PJSTGUIs.jpRevisedSchedule jpRevisedSchedule1;
    private PJSTGUIs.jpRevisedSchedule jpRevisedSchedule2;
    private PJSTGUIs.jpRevisedSchedule jpRevisedSchedule3;
    // End of variables declaration//GEN-END:variables
}
