/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PJSTGUIs;

/**
 *
 * @author jef35
 */
public class jfInstructorTimes extends javax.swing.JFrame {

    /**
     * Creates new form jfInstructorTimes
     */
    public jfInstructorTimes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMonday = new javax.swing.JLabel();
        jlTuesday = new javax.swing.JLabel();
        jlWednesday = new javax.swing.JLabel();
        jlThursday = new javax.swing.JLabel();
        jlFriday = new javax.swing.JLabel();
        jlSaturday = new javax.swing.JLabel();
        jlSunday = new javax.swing.JLabel();
        jspTimes = new javax.swing.JScrollPane();
        jtTimes = new javax.swing.JTextArea();
        jbSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlMonday.setText("Monday");

        jlTuesday.setText("Tuesday");

        jlWednesday.setText("Wednesday");

        jlThursday.setText("Thursday");

        jlFriday.setText("Friday");

        jlSaturday.setText("Saturday");

        jlSunday.setText("Sunday");
        jlSunday.setToolTipText("");

        jtTimes.setColumns(20);
        jtTimes.setRows(5);
        jspTimes.setViewportView(jtTimes);

        jbSend.setText("Send to Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSunday)
                            .addComponent(jlSaturday)
                            .addComponent(jlFriday)
                            .addComponent(jlThursday)
                            .addComponent(jlWednesday)
                            .addComponent(jlTuesday)
                            .addComponent(jlMonday))
                        .addGap(30, 30, 30)
                        .addComponent(jspTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jbSend)))
                .addGap(0, 96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlMonday)
                        .addGap(18, 18, 18)
                        .addComponent(jlTuesday)
                        .addGap(18, 18, 18)
                        .addComponent(jlWednesday)
                        .addGap(21, 21, 21)
                        .addComponent(jlThursday)
                        .addGap(18, 18, 18)
                        .addComponent(jlFriday)
                        .addGap(18, 18, 18)
                        .addComponent(jlSaturday)
                        .addGap(18, 18, 18)
                        .addComponent(jlSunday))
                    .addComponent(jspTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jbSend)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfInstructorTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfInstructorTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfInstructorTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfInstructorTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfInstructorTimes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSend;
    private javax.swing.JLabel jlFriday;
    private javax.swing.JLabel jlMonday;
    private javax.swing.JLabel jlSaturday;
    private javax.swing.JLabel jlSunday;
    private javax.swing.JLabel jlThursday;
    private javax.swing.JLabel jlTuesday;
    private javax.swing.JLabel jlWednesday;
    private javax.swing.JScrollPane jspTimes;
    private javax.swing.JTextArea jtTimes;
    // End of variables declaration//GEN-END:variables
}
