/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PJSTGUIs;

/**
 *
 * @author jef35
 */
public class jfInstructorInfo extends javax.swing.JFrame {

    /**
     * Creates new form jfInstructorInfo
     */
    public jfInstructorInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCampus = new javax.swing.JLabel();
        jlTerm = new javax.swing.JLabel();
        jlCourse = new javax.swing.JLabel();
        jcCampus = new javax.swing.JComboBox<>();
        jcTerm = new javax.swing.JComboBox<>();
        jcCourse = new javax.swing.JComboBox<>();
        jlAddCourse = new javax.swing.JLabel();
        jlDays = new javax.swing.JLabel();
        jlTimes = new javax.swing.JLabel();
        jlDepartment = new javax.swing.JLabel();
        jtDays = new javax.swing.JTextField();
        jtTimes = new javax.swing.JTextField();
        jtDepartment = new javax.swing.JTextField();
        jbAddCourse = new javax.swing.JButton();
        jlTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlCampus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCampus.setText("Campus:");

        jlTerm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlTerm.setText("Term:");

        jlCourse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCourse.setText("Course:");
        jlCourse.setToolTipText("");

        jcCampus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "University Park", "Abington", "Altoona", "Beaver", "Berks", "Brandywine", "Carlisle", "Dubois", "Erie (Behrend)", "Fayette", "Greater Allegheny", "Great Valley", "Harrisburg", "Hazleton", "Hershey", "Lehigh Valley", "Mont Alto", "New Kensington", "Penn College of Technology", "Schuylkill", "Scranton", "Shenango", "Wilkes-Barre", "York" }));

        jcTerm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spring 2021", "Summer 2021", "Fall 2021", "Spring 2022" }));

        jcCourse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlAddCourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlAddCourse.setText("Add a Course:");

        jlDays.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDays.setText("Days Available:");

        jlTimes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlTimes.setText("Times Available:");

        jlDepartment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDepartment.setText("Department:");

        jtDays.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtTimes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtDepartment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jbAddCourse.setBackground(new java.awt.Color(0, 0, 153));
        jbAddCourse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        jbAddCourse.setText("Add Course");

        jlTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTitle.setText("Instructor Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlDays)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtDays, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTimes)
                            .addComponent(jlDepartment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtTimes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTerm)
                            .addComponent(jlCourse)
                            .addComponent(jlCampus))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcTerm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcCampus, 0, 360, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbAddCourse)
                    .addComponent(jlAddCourse))
                .addGap(188, 188, 188))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jlTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCampus)
                    .addComponent(jcCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTerm)
                    .addComponent(jcTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCourse))
                .addGap(35, 35, 35)
                .addComponent(jlAddCourse)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDays)
                    .addComponent(jtDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTimes)
                    .addComponent(jtTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDepartment)
                    .addComponent(jtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jbAddCourse)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfInstructorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfInstructorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfInstructorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfInstructorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfInstructorInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddCourse;
    private javax.swing.JComboBox<String> jcCampus;
    private javax.swing.JComboBox<String> jcCourse;
    private javax.swing.JComboBox<String> jcTerm;
    private javax.swing.JLabel jlAddCourse;
    private javax.swing.JLabel jlCampus;
    private javax.swing.JLabel jlCourse;
    private javax.swing.JLabel jlDays;
    private javax.swing.JLabel jlDepartment;
    private javax.swing.JLabel jlTerm;
    private javax.swing.JLabel jlTimes;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTextField jtDays;
    private javax.swing.JTextField jtDepartment;
    private javax.swing.JTextField jtTimes;
    // End of variables declaration//GEN-END:variables
}
